name: Compile extension

on:
  pull_request:
    paths:
      - ".github/workflows/ci.*"
      - "ext/**"
      - package.xml
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/ci.*"
      - "ext/**"
      - package.xml
    tags-ignore:
      - "**"

jobs:
  compile:
    strategy:
      matrix:
        image:
          - php:8.0-cli
          - php:8.1-cli
          - php:8.2-cli
          - php:8.3-cli
          - php:8.4-cli
          - php:8.5-cli
          
    name: Image ${{ matrix.image }}
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          apt-get update -q
          apt-get install -qy gfortran liblapack-dev libopenblas-dev liblapacke-dev

      - name: Build PHP extension
        run: pie install

      - name: Enable PHP extension
        run: docker-php-ext-enable tensor_ext

      - name: Check for PHP startup warnings
        run: |
          php -d display_errors=stderr -d display_startup_errors=1 -d error_reporting=-1 -r ';' 2>/tmp/php-startup-warnings
          if [ -s /tmp/php-startup-warnings ]; then
            echo 'The PHP extension was successfully installed, but PHP raised these warnings:' >&2
            cat /tmp/php-startup-warnings >&2
            exit 1
          fi
          echo "PHP didn't raise any warnings at startup."

      - name: Inspect PHP extension
        run: php --ri tensor_ext

      - name: Validate composer.json
        run: composer validate

      - name: Install Dependencies
        run: composer install

      - name: Static Analysis
        run: composer analyze

      - name: Unit Tests
        run: composer test

      - name: Check Coding Style
        run: composer check
